body:
  - type: markdown
    attributes:
      value: |
        Takk for at du bidrar med å dokumentere behovet for en ny komponent 🎉
  - type: textarea
    id: description
    attributes:
      label: Beskriv komponenten
      value: |
        Beskriv komponenten og hvilket behov den dekker
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Legg ved et skjermbilde eller link til et eksempel
      value: |
        Skjermbilde eller link...
    validations:
      required: true

